<a href="https://colab.research.google.com/github/krishjoshi7/Pytorch-/blob/main/Pytorch_fundamental_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Accesing a  GPU

GPUs = faster computation on numbers,
thanks to CUDA + NVIDIA hardware + Pytorch woking behind the sence to make everything hunky dory(good)

# Getting a GPU
* Easisest  - Use Google Colab for a free Gpu (otions to upgrade as well)
* Use your own GPU - takes a little bit of setup and requires the  investment of purchasing a GPU
* Use cloud computing - GCP, AWS, Azure, these servies allow you to rent computer on the cloud and access them

for option 2 and 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up,
* To do this refer to PyTorch setup doucmentation

# Check for GPU access with PyTorch

In [1]:
#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

# Setup device agnostic code

In [2]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

 For Pytorch since it's capable of running computer on the GPU or CPU, it's best practice to setup device agnostic code :

 E.g run on GPU if avialable, else default to CPU

In [3]:
# Count number of devices
torch.cuda.device_count()

1

# Putting tensors (and models) on the GPU

* The reason we want our tensor/model on the GPU is because using a GPU result in faster computation

In [5]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Numpy only works with cpu

# Moving tensor back to the CPU

In [8]:
# If tensor is on GPU can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
# To fix the GPU tensor with Numpy issue, we can frist set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')