<a href="https://colab.research.google.com/github/krishjoshi7/Pytorch-/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch fundamentals

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to Tensors

creating tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# A scalar has no dimenssion for this we use command (.ndim)
scalar.ndim

0

torch.tensor()  *always copies data

 *if you want to avoid copy use :- detach() or use requries_grad_()

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#NOTE

In Ml/DL for variable name

we will be using scalar, vector with lower case

MATRIX, TENSOR will use upper case

#Random Tensors

Why random tensors ?

Random tensors are importan  beacuse

The way many nueral network learns is that they start with tensors fullof random numbers and then adjust thoes random numbers to better represent the data

`start with random numbers -> look at data -> update random number -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2486, 0.1221, 0.8538, 0.3223],
        [0.7237, 0.3850, 0.0866, 0.3449],
        [0.4202, 0.0424, 0.9378, 0.8327]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(224,224,3)) # height, width, colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.1429, 0.7241, 0.8294],
        [0.4780, 0.9254, 0.8573],
        [0.0386, 0.7552, 0.3430]])

# Zeros and Ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tenzors of all Ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

# Creating a range of tensor and tensor-like

In [ ]:
# use torch.range
torch.range(0, 10)

<ipython-input-27-0bc77e01e55b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#Note


torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use

torch.arange

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensor like
# this function is used to create zeros tensor of the same shape aa assinged tensor to it
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# TENSOR DATATYPE

To see datatypes go to torch.tensor
             or


#Note
Tensor datatype is one of the 3 big error you'll run into with pytorch & deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device



In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, # what datatype is the tennsor(e.g float32 or float16)
                               device=None, # what device is your tensor on
                                requires_grad=False) #whether or not to trace gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors (tensor attributes)


1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from tensor we can use `tensor.shape`
3. Tensor not on the right device - to get device(CPU/ GPU) from tensor we can use `tensor.device`

In [ ]:
# create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)

tensor([[0.8448, 0.7482, 0.1923, 0.1831],
        [0.3024, 0.9722, 0.1253, 0.8240],
        [0.9093, 0.5835, 0.2538, 0.8370]])


In [ ]:
# find out detail about some tensor
print(some_tensor)
print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.8448, 0.7482, 0.1923, 0.1831],
        [0.3024, 0.9722, 0.1253, 0.8240],
        [0.9093, 0.5835, 0.2538, 0.8370]])
datatype of tensor : torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on : cpu


# Manipulating Tensors (tensor operations)

Tensor operation includes :
 + Additions
 - Subtractions
 * multiplication (element-wise)
 * Division
 * Matrix multiplication




In [ ]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out python in built funtions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

#Matrix Multiplication

Two main ways of performing multiplication in nureal networks and deep learning


* Element-wise multiplication
* Matrix Multiplication(dot product)

There are two main rules that performing matrix multiplication needs to satisfy :

( 1 )  **INNER DIMENSIONS** must match:

* `(3, 2) @ (2,3)` this will work
* `(2, 3) @ (3'2)` This will work
* `(3, 2) @ (3,2)` This wont work


(2) The resulting matrix has the shape of ** Outer dimensions**:

* `(2,3) @ (3,2)` -> `(2, 2)`
* `(3,2) @ (2,3)` -> `(3, 3)`



In [ ]:
#torch.matmul(torch.rand(3,2), torch.rand(3,2))

# most common error in ml

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1085, 0.4676, 0.3426],
        [0.4042, 0.4415, 0.5765],
        [0.2813, 0.6345, 0.5773]])

In [ ]:
# Element wise multiplication
print (tensor, "*", tensor)
print(f"Equals : {tensor * tensor }")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
(1*1) + (2*2) + (3*3)

14

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)) :
  value += tensor[i] * tensor[i]
value

CPU times: user 1.18 ms, sys: 22 µs, total: 1.2 ms
Wall time: 2.55 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.15 ms, sys: 14 µs, total: 1.16 ms
Wall time: 4.73 ms


tensor(14)

#one of most common error in deep learning : shape error

In [ ]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B =torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

In [ ]:
tensor_A.shape

torch.Size([3, 2])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(it's an alias for writing less code)

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

A **Transpose** switches the axis or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Orignnal shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape} ")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension match")
print("Output:\n")
Output = torch.matmul(tensor_A, tensor_B.T)
print(Output)
print(f"\noutput shape : {Output.shape}")



Orignnal shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3]) 
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape : torch.Size([3, 3])


# Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.dtype

torch.int64

In [ ]:
#Find the min
torch.min(x)

tensor(1)

In [ ]:
# Find the max
torch.max(x)

tensor(91)

In [ ]:
# Find the mean
#torch.mean(x) this cannot run with long datatype we need to change it to other datatype
torch.mean(x.type(torch.float32))

tensor(46.)

#Note:
the `torch.mean()` function requires a tensor of flaot31 datatype to work


In [ ]:
x.type(torch.float32).mean()

tensor(46.)

In [ ]:

# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Finding the positional min and max

In [ ]:
#Find the position in tensor that has the minimum vale with argmin() -> returns index position of target

#tensor where the minimum value occurs

x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum vale with argmax() -> returns index position of target

#tensor where the maximum value occurs

torch.argmax(x)

tensor(9)

In [ ]:
x[9]

tensor(91)